name: bgg
description: >
  BoardGameGeek.com API Client for Dart and Flutter.
version: 0.1.0
authors:
  - Matan Lurey <matanl@google.com>
homepage: https://github.com/matanlurey/bgg.dart

environment:
  sdk: ">=1.22.0 <2.0.0"

dependencies:
  http: ^0.11.3+10
  meta: ^1.0.5
  xml: ^2.5.0

dev_dependencies:
  stack_trace: ^1.3.2
  test: ^0.12.20+12

